using System;
using System.Collections.Generic;

using Xamarin.Forms;
using Xamarin.Forms.Maps;
using static ServingFresh.Views.SelectionPage;
using static ServingFresh.Views.CheckoutPage;
using static ServingFresh.Views.SignUpPage;

namespace ServingFresh.Views
{
    public partial class ConfirmationPage : ContentPage
    {
        public ConfirmationPage()
        {
            InitializeComponent();
            cartItemsNumber.Text = purchase.getPurchaseItems().Count.ToString();
            contactMessage.Text = "If we have question. We will contact you at " + purchase.getPurchaseEmail() + " or " + purchase.getPurchasePhoneNumber();
            expectedDeliveryMessage.Text = "Your order will be delivered on: " + selectedDeliveryDate.deliveryTimeStamp.ToString("dddd, MMM dd, yyyy");
            PlaceLocationOnMap(double.Parse(purchase.getPurchaseLatitude()), double.Parse(purchase.getPurchaseLongitude()));
            ShowAutoGenereatedCredentials(purchase.getPurchaseEmail(), GetAutoGeneratedPasswordFrom(purchase.getPurchaseFirstName().Trim(), purchase.getPurchaseAddress().Trim()));
        }

        void PlaceLocationOnMap(double latitude, double longitude)
        {
            Position position = new Position(latitude, longitude);
            map.MapType = MapType.Street;
            var mapSpan = new MapSpan(position, 0.001, 0.001);
            Pin address = new Pin();
            address.Label = "Delivery Address";
            address.Type = PinType.SearchResult;
            address.Position = position;
            map.MoveToRegion(mapSpan);
            map.Pins.Add(address);
        }

        async void ShowAutoGenereatedCredentials(string userName, string tempPassword)
        {
            await DisplayAlert("Thank you for your purchase!", "Remeber you can access new features like rewards, history, and more by using the following credentials: ("+ userName+ ", " + tempPassword + ") ", "OK");
        }

        void ReturnToStore(System.Object sender, System.EventArgs e)
        {
            Application.Current.MainPage = new SelectionPage();
        }

        void SignIn(System.Object sender, System.EventArgs e)
        {
            Application.Current.MainPage = new LogInPage();
        }

        void NavigateToCartFromConfirmation(System.Object sender, System.EventArgs e)
        {
            NavigateToCart(sender, e);
        }
    }  
}
